#jangan recode yah kalau mau recode bisa pake api key sendiri:D
#recode ijin dulu yak jan script kiddie
import requests,json
import os
import hashlib
import pyfiglet
os.system('clear')
awal = pyfiglet.figlet_format("WanZ 1.0")
awal1 = pyfiglet.figlet_format("Covid-19 ID")
print(awal)
print("---------------------Menu Tools----------------------")
print("[1] Detect CMS Website")
print("[2] Reverse IP")
print("[3] Detect Theme WordPress")
print("[4] Encode MD5")
print("[5] Detect Hosting Site")
print("[6] Technology Detection")
print("----------------------------------------------------")
print(awal1)
cov19 = requests.get("https://covid19.mathdro.id/api/countries/indonesia")
print("Dikonfirmasi :",json.loads(cov19.content)['confirmed']['value'],"Orang",)
print("Sembuh :",json.loads(cov19.content)['recovered']['value'],"Orang",)
print("Meninggal :",json.loads(cov19.content)['deaths']['value'],"Orang",)
print("Terakhir Di Update :",json.loads(cov19.content)['lastUpdate'])
print("----------------------------------------------------")
pilih = input("Pilih No Tools: ")
if pilih =='1':
      print("____________________Detect CMS Website_____________________")
      print("____________________________________________________________")
      print("By : Wan5550")
      print("____________________________________________________________")
      teks = input("Masukan URL/Site : ")
      wan = requests.get("https://whatcms.org/API/CMS?key=6553a9f1701a12bb67ff827bf30b848090c198cbdc87884d3520fc03808121465fea77&url="+teks)
      print("Message :",json.loads(wan.content)['result']['msg'])
      print("Use CMS :",json.loads(wan.content)['result']['name'])
      print("Version :",json.loads(wan.content)['result']['version'])
elif pilih == '2':   
      print("-----------------------Reverse IP-----------------------")
      print("____________________________________________________________")
      print("By : Wan5550")
      print("____________________________________________________________")
      url = input("Masukan IP Web : ")
      connect = requests.get("https://api.hackertarget.com/reverseiplookup/?q="+url)
      print(connect.text)
      createfile = open("Hasil Rev IP.txt","w")
      createfile.write(connect.text)
      createfile.close()
      print("[+] Reverse IP Berhasil Silahkan Buka Folder Tools Ini Berada")
      print("[+] Hasil Dengan Nama : Hasil Rev.txt")
elif pilih == '3':
    print("-------------Detect Theme WordPress-------------")
    print("_________________________________________________________________")
    print("By : Wan5550")
    print("_________________________________________________________________")
    site = input("Masukan Site : ")
    wan5 = requests.get("https://www.themedetect.com/API/Theme?key=6553a9f1701a12bb67ff827bf30b848090c198cbdc87884d3520fc03808121465fea77&url="+site)
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("Message : ",json.loads(wan5.content)['result']['msg'])
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("Theme Name : ",json.loads(wan5.content)['results'][0]['theme_name'])
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("Author Theme : ",json.loads(wan5.content)['results'][0]['author'])
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("Version Theme : ",json.loads(wan5.content)['results'][0]['version'])
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("Theme URL : ",json.loads(wan5.content)['results'][0]['theme_uri'])
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("Description Theme : ",json.loads(wan5.content)['results'][0]['description'])
elif pilih == '4':
      print("____________________Encode MD5___________________________")
      print("____________________________________________________________")
      print("By : Wan5550")
      print("____________________________________________________________")
      input = input("Masukan Tulisan : ")
      str = input
      hasil = hashlib.md5(str.encode()) 
      print("Hasil MD5 :",hasil.hexdigest()) 
elif pilih == '5':
	print("____________________Detect Hosting Site_____________________")
	print("____________________________________________________________")
	print("By : Wan5550")
	print("____________________________________________________________")
	hostsite = input("Masukan Site :")
	wannaz = requests.get("https://www.who-hosts-this.com/API/Host?key=6553a9f1701a12bb67ff827bf30b848090c198cbdc87884d3520fc03808121465fea77&url="+hostsite)
	print("Message : ",json.loads(wannaz.content)['result']['msg'])
	print("IP : ",json.loads(wannaz.content)['results'][0]['ip'])
	print("Type : ",json.loads(wannaz.content)['results'][0]['type'])
	print("Host : ",json.loads(wannaz.content)['results'][0]['isp_name'])
elif pilih == '6':
	print("____________________Technology Detection____________________")
	print("By : Wan5550")
	print("____________________________________________________________")
	techsite = input("Masukan Site/URL :")
	techwan = requests.get("https://whatcms.org/API/Tech?key=6553a9f1701a12bb67ff827bf30b848090c198cbdc87884d3520fc03808121465fea77&url="+techsite)
	print("Message :",json.loads(techwan.content)['result']['msg'])
	print("Nama :",json.loads(techwan.content)['results'][0]['name'])
	print("Kategori :",json.loads(techwan.content)['results'][0]['categories'])
	
	

else:
	print("Pilih No Sesuai Yang Ada Di Menu")
